### ISSUE TITLE
Czy będzie update do najnowszej dok?

### ISSUE THREAD

**Issue by kanlukasz** [michalsn/laravel-docs-pl#9]
Cześć, czy jest szansa na zaktualizowanie docs do najnowszego Laravela?

**Comment by michalsn** [comment]
Raczej nie.

Brak "zasobów ludzkich" do przeprowadzenia takiej operacji... do tego aktualizacje angielskiej wersji są przeprowadzane dosyć często, więc dochodziłoby uważne śledzenie tego wszystkiego...

Im wcześniej "początkujący" wyrobią sobie nawyk czytania oryginalnej dokumentacji, tym lepiej. A cała reszta i tak już z niej korzysta.

**Comment by kanlukasz** [comment]
Oczywiście masz racje. Dzięki za info
